modulo03-python-web-com-django/20221209-aula05/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls"))
]

modulo03-python-web-com-django/20221209-aula05/polls/urls.py
from django.urls import path

# import relativo
# A partir da pasta onde o arquivo está, import o módulo views
from .views import index, detail, results, vote, statistics, comment
# namespace
app_name = "polls"

urlpatterns = [
    path("", index, name="index"),
    # question_id é um parâmetro passado via URL
    # Ou seja, ele pode mudar a qualquer chamada
    path("<int:question_id>/", detail, name="detail"),
    path("<int:question_id>/results/", results, name="results"),
    path("<int:question_id>/vote/", vote, name="vote"),
    path("<int:question_id>/comment/", comment, name="comment"),
    path("statistics/", statistics, name="statistics")
]

modulo03-python-web-com-django/20221209-aula05/polls/models.py
from django.db import models


class Question(models.Model):

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('Data de publicação')

    def __str__(self):
        return self.question_text

    class Meta:
        db_table = 'tb_questions'


class Choice(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

    class Meta:
        db_table = 'tb_choices'


class Comment(models.Model):

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    text = models.TextField()

    class Meta:
        db_table = "tb_comments"

modulo03-python-web-com-django/20221209-aula05/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.db.models import Sum

from polls.models import Question, Choice, Comment


# function-based view
def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")

    context = {
        "latest_question_list": latest_question_list
    }
    return render(request, "polls/index.html", context)


def detail(request, question_id):
    # get_object_or_404 retorna um objeto caso exista. Se não existir, gera
    # um erro 404
    question = get_object_or_404(Question, pk=question_id)

    # primary key -> chave primária
    # question = Question.objects.get(pk=question_id)

    context = {
        "question": question
    }
    return render(request, "polls/detail.html", context)


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})


def vote(request, question_id):

    # Carregamos um objeto Question da tabela tb_questions, a partir do question_id
    question = get_object_or_404(Question, pk=question_id)
    try:
        # Abaixo tentamos carregar um objeto choice a partir do valor da opção choice que vem
        # do formulário. 'choice' é o nome dos elementos radio button no formulário. Aqui
        # receberemos o valor que estiver em 'value'
        # POST é um dicionários com os campos que foram enviados de um formulário utilizando o
        # método POST
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        context = {
            "question": question,
            "error_message": "Você não escolheu uma opção para votar"
        }
        return render(request, "polls/detail.html", context)

    else:
        # Incrementamos a quantidade de votos da opção selecionada em 1
        selected_choice.votes += 1

        # Salvamos (atualizamos) o objeto com a nova quantidade de votos
        selected_choice.save()


        # Por boas práticas, sempre que um usuário enviar dados via POST, redirecionamos o usuário
        # para outra página, por isso utilizamos o HttpResponseRedirect
        # A função reverse gera a URL a partir do nome da rota. Se essa rota precisar receber
        # algum tipo de parâmetro, passamos pelo argumento args

        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))


def statistics(request):

    total_questions = Question.objects.count()
    total_choices = Choice.objects.count()
    most_voted_choices = Choice.objects.order_by("-votes")[:3]

    questions_with_more_votes = Question.objects.annotate(
        total=Sum("choice__votes")
    ).order_by("-total")[:3]

    questions_with_less_votes = Question.objects.annotate(
        total=Sum("choice__votes")
    ).order_by("total")[:3]

    context = {
        "total_questions": total_questions,
        "total_choices": total_choices,
        "most_voted_choices": most_voted_choices,
        "questions_with_more_votes": questions_with_more_votes,
        "questions_with_less_votes": questions_with_less_votes
    }

    return render(request, "polls/statistics.html", context)


def comment(request, question_id):
    text = request.POST['text']
    question = get_object_or_404(Question, pk=question_id)

    comment = Comment(
        question=question, text=text
    )

    comment.save()

    return HttpResponseRedirect(
        reverse("polls:results", args=(question.id,))
    )

modulo03-python-web-com-django/20221209-aula05/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
    {% csrf_token %}
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <br>
    <input type="submit" value="Votar">
    <hr>
    <a href="{% url 'polls:results' question.id %}">Ir para os resultados</a><br>
    <a href="{% url 'polls:index' %}">Voltar para a página principal</a>
</form>

modulo03-python-web-com-django/20221209-aula05/polls/templates/polls/index.html
<h1>Quizzes</h1>
<hr>

{% if latest_question_list %}
    <ul>
        {% for question in latest_question_list %}
            <li>
                <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>Não há perguntas a serem exibidas!</p>
{% endif %}

<hr>
<a href="{% url 'polls:statistics' %}">Clique para acessar as estatísticas</a>

modulo03-python-web-com-django/20221209-aula05/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>
<hr>

<ul>
    {% for choice in question.choice_set.all %}
        <li>
            {{ choice.choice_text }} -- {{ choice.votes }} voto{{ choice.votes|pluralize }}
        </li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Deseja votar novamente?</a><br>
<a href="{% url 'polls:index' %}">Voltar para a página principal</a>
<hr>

<form action="{% url 'polls:comment' question.id %}" method="post">
    {% csrf_token %}
    <textarea name="text" cols="50" rows="10"></textarea>
    <br><br>
    <input type="submit" value="Enviar">
    <hr>
</form>

{% if question.comment_set.all %}
    <h2>Comentários</h2>
    <ul>
        {% for comment in question.comment_set.all %}
            <li>{{ comment.text }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>Sem comentários publicados.</p>
{% endif %}

modulo03-python-web-com-django/20221209-aula05/polls/templates/polls/statistics.html
<h1>Estatísticas do site</h1>
<hr>

<h3>1) Total de perguntas cadastradas no banco: {{ total_questions }}</h3>

<h3>2) Total de opções cadastradas no banco: {{ total_choices }}</h3>

<h3>3) 3 Opções mais votadas:</h3>
<ul>
    {% for choice in most_voted_choices %}
        <li>{{ choice.choice_text }} -- {{ choice.votes }} -- {{ choice.question }}</li>
    {% endfor %}
</ul>

<h3>4) 3 Perguntas com mais votos</h3>
<ul>
    {% for question in questions_with_more_votes %}
        <li>{{ question }} -- {{ question.total }}</li>
    {% endfor %}
</ul>

<h3>5) 3 Perguntas com menos votos</h3>
<ul>
    {% for question in questions_with_less_votes %}
        <li>{{ question }} -- {{ question.total }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:index' %}">Voltar para a página principal</a>